# Generated by Django 3.0.2 on 2020-02-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_idea',
            new_name='add_idea1',
        ),
        migrations.RenameModel(
            old_name='user_profile',
            new_name='user_profile1',
        ),
    ]
