# Generated by Django 3.0.2 on 2020-02-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0002_auto_20200201_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_idea1',
            new_name='add_idea',
        ),
        migrations.RenameModel(
            old_name='user_profile1',
            new_name='user_profile',
        ),
    ]
