# Generated by Django 3.0.2 on 2020-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0003_auto_20200201_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_idea_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('domain', models.TextField(max_length=200)),
                ('ncollab', models.IntegerField()),
                ('link', models.TextField(max_length=300)),
                ('about', models.TextField(max_length=1000)),
                ('nlike', models.IntegerField()),
                ('nviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_profile_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=200)),
                ('lname', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('contact', models.IntegerField()),
                ('password', models.TextField(max_length=200)),
                ('qualification', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=300)),
                ('city', models.TextField(max_length=200)),
                ('country', models.TextField(max_length=200)),
                ('postal_code', models.IntegerField()),
                ('about_me', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='add_idea',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
