# Generated by Django 3.0.2 on 2020-02-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0004_auto_20200201_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_idea_final',
            new_name='add_idea',
        ),
        migrations.RenameModel(
            old_name='user_profile_final',
            new_name='user_profile',
        ),
    ]
