# Generated by Django 3.0.2 on 2020-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0006_auto_20200201_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('gst_no', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('password', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='register_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('contact', models.IntegerField()),
                ('password', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='add_idea1',
        ),
        migrations.DeleteModel(
            name='user_profile1',
        ),
    ]
