# Generated by Django 3.0.2 on 2020-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0008_add_idea1_user_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_investor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('gst_no', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('password', models.TextField(max_length=200)),
                ('typeof', models.TextField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='register_user1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('contact', models.IntegerField()),
                ('password', models.TextField(max_length=200)),
                ('typeof', models.TextField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='register_investor',
        ),
        migrations.DeleteModel(
            name='register_user',
        ),
    ]
